-- Expand Bese26 marketplace categories without changing existing tables or listing data.
-- Existing slugs are upserted; new parents and children are added idempotently.

insert into public.categories (name, slug, icon, sort_order, is_active) values
  ('Computers & Accessories', 'computers-accessories', 'laptop', 100, true),
  ('Robotics & Electronics', 'robotics-electronics', 'cpu', 110, true),
  ('Solar & Power', 'solar-power', 'sun', 120, true),
  ('Home Appliances', 'home-appliances', 'washing-machine', 130, true),
  ('Tools & Hardware', 'tools-hardware', 'hammer', 140, true),
  ('Construction & Building', 'construction-building', 'building-2', 150, true),
  ('Industrial & Business Equipment', 'industrial-business-equipment', 'factory', 160, true),
  ('Safety & Security', 'safety-security', 'shield-check', 170, true),
  ('Baby & Kids', 'baby-kids', 'baby', 180, true),
  ('Sports & Fitness', 'sports-fitness', 'dumbbell', 190, true),
  ('Food & Groceries', 'food-groceries', 'shopping-basket', 200, true),
  ('Books, Media & Games', 'books-media-games', 'book-open', 210, true),
  ('Office & School', 'office-school', 'notebook-tabs', 220, true),
  ('Musical Instruments', 'musical-instruments', 'music-2', 230, true),
  ('Travel & Luggage', 'travel-luggage', 'luggage', 240, true),
  ('Pets & Animals', 'pets-animals', 'paw-print', 250, true),
  ('Spare Parts & Accessories', 'spare-parts-accessories', 'settings-2', 260, true),
  ('Other', 'other', 'ellipsis', 9999, true)
on conflict (slug) do update set
  name = excluded.name,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  is_active = true;

insert into public.categories (parent_id, name, slug, icon, sort_order, is_active)
select c.id, x.name, x.slug, x.icon, x.sort_order, true
from public.categories c
join (values
  ('phones-tablets', 'Phone Accessories', 'cable', 'phone-accessories', 30),
  ('phones-tablets', 'Wearables & Smartwatches', 'watch', 'wearables-smartwatches', 40),
  ('phones-tablets', 'Mobile Network Devices', 'router', 'mobile-network-devices', 50),
  ('electronics', 'Cameras & Photography', 'camera', 'cameras-photography', 30),
  ('electronics', 'Game Consoles', 'gamepad-2', 'game-consoles', 40),
  ('electronics', 'Printers & Scanners', 'printer', 'printers-scanners', 50),
  ('electronics', 'Computer Monitors', 'monitor', 'computer-monitors', 60),
  ('computers-accessories', 'Desktop Computers', 'monitor', 'desktop-computers', 10),
  ('computers-accessories', 'Computer Accessories', 'keyboard', 'computer-accessories', 20),
  ('computers-accessories', 'Computer Parts', 'microchip', 'computer-parts', 30),
  ('computers-accessories', 'Networking Equipment', 'router', 'networking-equipment', 40),
  ('robotics-electronics', 'Arduino & Microcontrollers', 'cpu', 'arduino-microcontrollers', 10),
  ('robotics-electronics', 'Raspberry Pi & SBCs', 'cpu', 'raspberry-pi-sbcs', 20),
  ('robotics-electronics', 'Sensors & Modules', 'activity', 'sensors-modules', 30),
  ('robotics-electronics', 'Motors & Servos', 'rotate-cw', 'motors-servos', 40),
  ('robotics-electronics', 'Robotics Kits', 'bot', 'robotics-kits', 50),
  ('robotics-electronics', 'IoT & Automation', 'wifi', 'iot-automation', 60),
  ('robotics-electronics', 'PCBs & Electronic Components', 'circuit-board', 'pcbs-electronic-components', 70),
  ('robotics-electronics', '3D Printing & CNC', 'printer', '3d-printing-cnc', 80),
  ('robotics-electronics', 'Drones & UAVs', 'drone', 'drones-uavs', 90),
  ('solar-power', 'Solar Panels', 'sun', 'solar-panels', 10),
  ('solar-power', 'Inverters', 'zap', 'inverters', 20),
  ('solar-power', 'Batteries & Storage', 'battery-charging', 'batteries-storage', 30),
  ('solar-power', 'Charge Controllers', 'gauge', 'charge-controllers', 40),
  ('solar-power', 'Generators', 'fuel', 'generators', 50),
  ('solar-power', 'UPS & Power Stations', 'battery', 'ups-power-stations', 60),
  ('solar-power', 'Solar Cables & Accessories', 'cable', 'solar-cables-accessories', 70),
  ('home-appliances', 'Refrigerators & Freezers', 'refrigerator', 'refrigerators-freezers', 10),
  ('home-appliances', 'Washing Machines', 'washing-machine', 'washing-machines', 20),
  ('home-appliances', 'Cookers & Kitchen Appliances', 'chef-hat', 'cookers-kitchen-appliances', 30),
  ('home-appliances', 'Fans & Air Conditioners', 'fan', 'fans-air-conditioners', 40),
  ('home-appliances', 'Small Home Appliances', 'coffee', 'small-home-appliances', 50),
  ('tools-hardware', 'Power Tools', 'drill', 'power-tools', 10),
  ('tools-hardware', 'Hand Tools', 'wrench', 'hand-tools', 20),
  ('tools-hardware', 'Plumbing Tools & Supplies', 'pipette', 'plumbing-tools-supplies', 30),
  ('tools-hardware', 'Electrical Tools & Supplies', 'plug', 'electrical-tools-supplies', 40),
  ('construction-building', 'Building Materials', 'bricks', 'building-materials', 10),
  ('construction-building', 'Doors, Windows & Roofing', 'door-open', 'doors-windows-roofing', 20),
  ('construction-building', 'Paints & Finishing', 'paint-bucket', 'paints-finishing', 30),
  ('construction-building', 'Plumbing & Water Systems', 'pipette', 'plumbing-water-systems', 40),
  ('industrial-business-equipment', 'Restaurant & Catering Equipment', 'utensils', 'restaurant-catering-equipment', 10),
  ('industrial-business-equipment', 'Farm & Processing Equipment', 'factory', 'farm-processing-equipment', 20),
  ('industrial-business-equipment', 'Printing & Packaging Equipment', 'printer', 'printing-packaging-equipment', 30),
  ('industrial-business-equipment', 'Generators & Industrial Power', 'zap', 'generators-industrial-power', 40),
  ('safety-security', 'CCTV & Surveillance', 'cctv', 'cctv-surveillance', 10),
  ('safety-security', 'Access Control & Alarms', 'lock-keyhole', 'access-control-alarms', 20),
  ('safety-security', 'Fire Safety Equipment', 'flame', 'fire-safety-equipment', 30),
  ('baby-kids', 'Baby Clothing & Accessories', 'baby', 'baby-clothing-accessories', 10),
  ('baby-kids', 'Toys & Games', 'toy-brick', 'toys-games', 20),
  ('baby-kids', 'School Supplies for Kids', 'pencil', 'school-supplies-kids', 30),
  ('sports-fitness', 'Gym & Fitness Equipment', 'dumbbell', 'gym-fitness-equipment', 10),
  ('sports-fitness', 'Sportswear & Shoes', 'footprints', 'sportswear-shoes', 20),
  ('sports-fitness', 'Outdoor & Camping', 'tent-tree', 'outdoor-camping', 30),
  ('food-groceries', 'Grains & Staple Foods', 'wheat', 'grains-staple-foods', 10),
  ('food-groceries', 'Drinks & Beverages', 'cup-soda', 'drinks-beverages', 20),
  ('food-groceries', 'Packaged Foods', 'package', 'packaged-foods', 30),
  ('books-media-games', 'Books & Textbooks', 'book-open', 'books-textbooks', 10),
  ('books-media-games', 'Video Games & Accessories', 'gamepad-2', 'video-games-accessories', 20),
  ('books-media-games', 'Movies & Music', 'disc-3', 'movies-music', 30),
  ('office-school', 'Office Furniture', 'briefcase-business', 'office-furniture', 10),
  ('office-school', 'Stationery & Supplies', 'notebook-pen', 'stationery-supplies', 20),
  ('office-school', 'School Textbooks', 'graduation-cap', 'school-textbooks', 30),
  ('musical-instruments', 'Keyboards & Pianos', 'piano', 'keyboards-pianos', 10),
  ('musical-instruments', 'Guitars & String Instruments', 'guitar', 'guitars-string-instruments', 20),
  ('musical-instruments', 'Drums & Percussion', 'drum', 'drums-percussion', 30),
  ('travel-luggage', 'Travel Bags & Suitcases', 'luggage', 'travel-bags-suitcases', 10),
  ('travel-luggage', 'Travel Accessories', 'plane', 'travel-accessories', 20),
  ('pets-animals', 'Pet Supplies', 'bone', 'pet-supplies', 10),
  ('pets-animals', 'Livestock & Poultry', 'bird', 'livestock-poultry', 20),
  ('spare-parts-accessories', 'Vehicle Spare Parts', 'car-front', 'vehicle-spare-parts', 10),
  ('spare-parts-accessories', 'Phone & Computer Parts', 'microchip', 'phone-computer-parts', 20),
  ('spare-parts-accessories', 'Machinery Spare Parts', 'settings-2', 'machinery-spare-parts', 30)
) as x(parent_slug, name, icon, slug, sort_order) on c.slug = x.parent_slug
on conflict (slug) do update set
  parent_id = excluded.parent_id,
  name = excluded.name,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  is_active = true;

-- Keep the catch-all category at the end of every category selector.
update public.categories set sort_order = 9999, is_active = true where slug = 'other';
